# Generated by Django 4.2 on 2024-10-30 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите категорию продукта', max_length=20, verbose_name='Категория продукта')),
            ],
        ),
        migrations.CreateModel(
            name='proizvoditel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите производителя: ', max_length=20, verbose_name='Производитель')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название продукта: ', max_length=100, verbose_name='Название продукта')),
                ('price', models.CharField(help_text='Введите цену продукта: ', max_length=100, verbose_name='Цена')),
                ('kcal', models.PositiveIntegerField(blank=True, help_text='Введите калорийность продукта: ', null=True, verbose_name='Калорийность')),
                ('categories', models.ForeignKey(help_text='Выберите категорию продукта: ', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='Категория')),
                ('proizvoditel', models.ForeignKey(help_text='Выберите производителя: ', null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.proizvoditel', verbose_name='Производитель')),
            ],
        ),
    ]
