# Generated by Django 4.2 on 2024-10-30 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
