# Generated by Django 4.2 on 2024-10-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение продукта:', null=True, upload_to='products/', verbose_name='Изображение'),
        ),
    ]
