# Generated by Django 4.2 on 2024-11-21 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение продукта:', upload_to='static/images', verbose_name='Изображение'),
        ),
    ]
