# Generated by Django 4.2 on 2024-11-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='kcal',
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(default='Описание отсутствует.', help_text='Введите описание продукта: ', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите скидку на продукт: ', max_digits=5, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Введите цену продукта: ', max_digits=10, verbose_name='Цена'),
        ),
    ]
