# Generated by Django 4.2 on 2024-11-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='country',
        ),
        migrations.RemoveField(
            model_name='deliveryaddress',
            name='postal_code',
        ),
    ]
