# Generated by Django 4.2 on 2024-11-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидание'), ('processing', 'Обработка'), ('ready', 'Готов'), ('delivered', 'Доставлен')], default='Магазин не существует вы олух', max_length=20),
        ),
    ]
