# Generated by Django 4.2 on 2024-12-01 14:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Телефонный номер должен быть введен в формате: '+999999999'. Допускается до 15 цифр.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
